# I use ENV variables to name my containers and set the ports
# to change, replate it here or in .env file
version: '2'
services:
  php:
    container_name: ${APP_NAME}-php
    image: jlamim/php7-nginx
    volumes:
     - ./src:/var/www/src
    ports:
     - ${HTTP_PORT}:80
     - ${HTTPS_PORT}:443
volumes:
  data:
    driver: local
